name: Scan

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
#     - name: Setup Java JDK
#       uses: actions/setup-java@v1.3.0
#       with:
#         java-version: 1.8
#     - name: Install dependencies
#       run: |
#         mvn clean install
    - uses: AppThreat/sast-scan-action@master
      with:
        type: "java"
    - name: Perform ShiftLeft Scan
      uses: ShiftLeftSecurity/scan-action@master
      with:
        type: "java"
      env:
#        WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true


